package com.revature.controller;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.security.authentication.AuthenticationManager;
import org.springframework.security.authentication.UsernamePasswordAuthenticationToken;
import org.springframework.web.bind.annotation.CrossOrigin;
import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.PostMapping;
import org.springframework.web.bind.annotation.RequestBody;
import org.springframework.web.bind.annotation.RestController;

import com.revature.models.AuthRequest;
import com.revature.util.JwtUtil;

@RestController
public class WelcomeController {

	@Autowired
	private JwtUtil jwtUtil;

	@Autowired
	private AuthenticationManager authenticationManager;

	/**
	 * In order to access this end point, we need
	 * to pass a JWT token which is only generated by the
	 * method generateToken() which accepts a username and password.
	 * @return
	 */
	@GetMapping("/")
	public String welcome() {
		return "Hello Spring Security!";
	}

	@PostMapping("/authenticate")
	public String generateToken(@RequestBody AuthRequest authRequest) throws Exception {

		/**
		 * For the user login, once the authentication request reached the
		 * authentication filter, it will extract the username and password from the
		 * request payload. Spring security will create an Authentication object based
		 * on the username and password.
		 */
		try {
			authenticationManager.authenticate(
					new UsernamePasswordAuthenticationToken(authRequest.getUsername(), authRequest.getPassword()));
			
		  	
		} catch (Exception ex) {
			throw new Exception("inavalid username/password");
		}

		/**
		 * If no exception is thrown, generate a token (in JSON format, 
		 * of course) to return to the client
		 */
		return jwtUtil.generateToken(authRequest.getUsername());
	}
}
